### ISSUE TITLE
Hello, what is your email address? I want to contact you for some technical questions

### ISSUE THREAD

**Issue by shizu2014** [valeriyKovalevskiy/PuzzleGame#1]
Hello, what is your email address?
I want to contact you for some technical questions

**Comment by valeriyKovalevskiy** [comment]
Hi. You can ask here if needed

Отправлено с iPhone

**Comment by shizu2014** [comment]
Hello there
May I ask where did you get the deeplink link?
I downloaded your application code
Did not get a link to deeplink
I want to ask how to configure this

**Comment by valeriyKovalevskiy** [comment]
I configure deep link inside Facebook dependency files 

Отправлено с iPhone

**Comment by shizu2014** [comment]
How much can your app sell?
Or are you working for the company

**Comment by valeriyKovalevskiy** [comment]
It’s my teams projects where i took part earlier.

**Comment by shizu2014** [comment]
Does anyone there need this product?
I can make
Is there a charge for Facebook to create ads using deep links?
When I create it, let me top up before I can use it

**Comment by valeriyKovalevskiy** [comment]
Probably this product is on AppStore now. I just download on github page last build of this game I have on my Mac. As for Facebook ads - I have no access to files with implementation 

Отправлено с iPhone

**Comment by shizu2014** [comment]
Is there an app in your area that needs this kind of switching link?

**Comment by valeriyKovalevskiy** [comment]
Idk actually. But if needed you can use all of the code

Отправлено с iPhone
